### ISSUE TITLE
Query is basically slow

### ISSUE THREAD

**Issue by karolyczovek** [FlxPeters/netbox-plugin-prometheus-sd#186]
curl -Li  ${NETBOX_URL}/api/plugins/prometheus-sd/devices?role=server&status=active&limit=100 -H "Authorization: Token $NETBOX_TOKEN" -H "Content-Type: application/json; indent=4" -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 47924  100 47924    0     0    873      0  0:00:54  0:00:54 --:--:-- 10523

real    0m54.860s
user    0m0.078s
sys     0m0.015s
root@instance-20240429-121233:~/netbox-docker# 

I have ca 50 devices listed, netbox version is 4.0.5

**Comment by FlxPeters** [comment]
Duplicate of #156 

50 devices shouldn't be an issue. There are some bottlenecks when it comes to > 1000 devices.

What kind of system is Netbox running on, and can you make sure it's not a database issue or something like that?
The raw curl command is too less information for a proper problem analysis.

**Comment by karolyczovek** [comment]
It's bare 4.0.5 netbox-docker, 8G RAM with 4 cores, the UI is generally responsive, also the generic API is quite fast as ansibe is using it for inventory. what details do you need?

**Comment by FlxPeters** [comment]
The specs sound reasonable. To be honest, i, can't analyze your Netbox performance. There are too many possible sources.
If you can point out a specific part in the code which causes a problem, we can talk about it.
Otherwise, this issue is not actionable.

There are plenty of profiling options:
* https://medium.com/kami-people/profiling-in-django-9f4d403a394f
* SQL (slow) query
* anything that help you to understand on which part of the code time is wasted.

**Comment by FlxPeters** [comment]
If this doesn't work there is a workaround if you have really many devices: https://github.com/FlxPeters/netbox-plugin-prometheus-sd/issues/156#issuecomment-1922766541
