### ISSUE TITLE
Feat: Add custom fields to enable prometheus for IP and specify port

### ISSUE THREAD

**Issue by phpfs** [FlxPeters/netbox-plugin-prometheus-sd#24]
Dear @FlxPeters,

thank you very much for bringing this plugin to life!

For our usage, it would be beneficial if the following two features were available:

1. Read a custom field boolean `prometheus-sd_enable` and only show the entry if the box is ticked (default: `true`).  
2. Read a custom field integer `prometheus-sd_port` that will specify the exporter's port for this entry (default: `9100`).  

Personally, I'd leave it up to the users to decide wether they want to add the custom fields by hand. As both fields have sane defaults, existing installations should not face any issues.

What do you think? Would these be helpful additions to the plugin? :)

Best, phpfs

**Comment by FlxPeters** [comment]
Hey and thanks for your feedback. Custom fields in Netbox are a delicate topic. Some love them, others not. 
The approach of this plugin to work out of the box without any special configuration. But i have some ideas how to solve this: 

1. Try to use opt-in filters for service discovery. I have had good experience with tags as a filter criteria. Also services work pretty fine. Both are filterable using the Netbox API. For your example this means: Add a Service named `node-exporter` to each of your monitored devices or VMs and use this as a filter criteria in Prometheus:

```
- job_name: node_exporter
  ...
  relabel_configs:
  - source_labels: [__meta_netbox_services]
    separator: ;
    regex: .*(node-exporter|node_exporter).*
    replacement: $1
    action: keep
 - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __address__
    replacement: ${1}:9100
    action: replace
  http_sd_configs:
    url: https://<netbox-uri>/api/plugins/prometheus-sd/virtual-machines?status=active
```

2. The port is a bit more tricky because Netbox services can define range of ports and not a single port since some time. Due to this i use static port configs at the moment (address label in the example). Maybe we can export the service with port range as a separate label. Do you have any suggestion for a matching format which is regexable? 

Another approach would be to export custom fields as labels. At least simple types should be no problem, text fields could get a problem.
